<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Tag: gbk | AoboSir 博客]]></title>
  <link href="http://aobojaing.github.io/tags/gbk/atom.xml" rel="self"/>
  <link href="http://aobojaing.github.io/"/>
  <updated>2016-12-14T18:50:17+08:00</updated>
  <id>http://aobojaing.github.io/</id>
  <author>
    <name><![CDATA[Aobo Jaing]]></name>
    
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[Python3 解决编码问题：  UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position xxx: illegal multibyte sequence --- 当执行爬虫将爬取信息打印到终端时出现的编码错误]]></title>
    <link href="http://aobojaing.github.io/blog/2016/12/08/python3-UnicodeEncodeError-gbk-codec-can't-encode-character-xa9/"/>
    <updated>2016-12-08T06:38:45+08:00</updated>
    <id>http://aobojaing.github.io/blog/2016/12/08/python3-UnicodeEncodeError-gbk-codec-can't-encode-character-xa9</id>
    <content type="html"><![CDATA[<hr />

<h2>开发环境</h2>

<ul>
<li>Python第三方库：lxml、Twisted、pywin32、scrapy</li>
<li>Python 版本：python-3.5.0-amd64</li>
<li>PyCharm软件版本：pycharm-professional-2016.1.4</li>
<li>电脑系统：Windows 10 64位</li>
</ul>


<p>如果你还没有搭建好开发环境，请到<a href="http://www.aobosir.com/blog/2016/11/26/python3-large-web-crawler-001-Build-development-environment/">这篇博客</a>。</p>

<hr />

<p>当使用Scrapy写爬虫项目的时候，当我们爬取某些中文网站，然后在DOS终端中打印爬取的网页源代码的时候，会出现各式各样的编码错误，今天，我又遇到一种编码错误，下面我将这个错误和对应的解决办法记录下来。</p>

<p>爬取的目标网址：<a href="http://blog.csdn.net/github_35160620/article/details/53353672">http://blog.csdn.net/github_35160620/article/details/53353672</a></p>

<p>出现错误的代码：</p>

<pre><code class="python">    def next(self, response):
        body_data = response.body.decode('utf-8', 'ignore')
        print(body_data)
        pass
</code></pre>

<p>执行：来到对应的爬虫项目路径下，执行：</p>

<pre><code>scrapy crawl 爬虫名字
</code></pre>

<p>在出现的调试信息中你可以看到一个编码错误：</p>

<pre><code>    print(body_data)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 6732: illegal multibyte sequence
</code></pre>

<p>通过查看，这个<a href="http://www.codetable.net/hex/a9"><code>u'xa9'</code> Unicode编码所表示的字符是：<code>©</code></a>。</p>

<p><img src="/images/2016-12-8-python3-UnicodeEncodeError-gbk-codec-can't-encode-character-xa9/1481149755580.png" alt="Alt text" /></p>

<p>可以解决这个错误的方法：</p>

<p>将上面的代码修改为：</p>

<pre><code class="python">    def next(self, response):
        body_data = response.body.decode('utf-8', 'ignore').replace(u'\xa9', u'')
        print(body_data)
        pass
</code></pre>

<p>现在运行这个程序<code>scrapy crawl 爬虫名字 --nolog</code>，上面的编码错误就没有。成功的输出了爬取的网页的源代码。</p>
]]></content>
  </entry>
  
  <entry>
    <title type="html"><![CDATA[Learning Python 015 解决问题：读取文件时，出现乱码或者“UnicodeDecodeError  'gbk' codec can't decode byte 0xXX in position XX: incomplete multibyte sequence” 错误]]></title>
    <link href="http://aobojaing.github.io/blog/2016/11/29/Python-read-file-Garbled-UnicodeDecodeError-gbk-codec-cant-decode-error/"/>
    <updated>2016-11-29T19:18:27+08:00</updated>
    <id>http://aobojaing.github.io/blog/2016/11/29/Python-read-file-Garbled-UnicodeDecodeError-gbk-codec-cant-decode-error</id>
    <content type="html"><![CDATA[<hr />

<ul>
<li>使用的电脑系统：Windows 10 64位</li>
<li>使用的开发集成环境：PyCharm 2016.1.4</li>
<li>使用的Python的版本：python 3.5.0</li>
</ul>


<hr />

<h2>出现的错误</h2>

<p>读取文件时，出现<strong>乱码</strong>或者<code>UnicodeDecodeError: 'gbk' codec can't decode byte 0xXX in position XX: incomplete multibyte sequence</code> 错误</p>

<hr />

<h2>出现错误的原因</h2>

<p>这两个错误可能会出现一个，两个错误的出现的原因是一样的：当我们使用了一个不正确的编码方式去读取一个不是用这个编码方式编码的文件时，轻者出现乱码，重者出现<code>UnicodeDecodeError</code>错误。</p>

<hr />

<h2>模拟错误发生现场</h2>

<pre><code class="python">file = open('newfile.txt', 'w', encoding='utf-8')
file.write('你好，AoboSir.')
file.close()
file = open('newfile.txt', 'r')
print(file.read())
file.close()
</code></pre>

<p>运行输出：</p>

<pre><code>浣犲ソ锛孉oboSir.
</code></pre>

<hr />

<pre><code class="python">file = open('newfile.txt', 'w', encoding='utf-8')
file.write('你好，AoboSir。')
file.close()
file = open('newfile.txt', 'r')
print(file.read())
file.close()
</code></pre>

<p>运行输出：</p>

<pre><code>Traceback (most recent call last):
  File "D:/WorkSpace/test_ws/demo/learning_python_15.py", line 6, in &lt;module&gt;
    print(file.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 35: incomplete multibyte sequence
</code></pre>

<hr />

<h2>解决办法</h2>

<p>读取文件时，指定正确的编码方式：</p>

<pre><code class="python">file = open('newfile.txt', 'r', encoding='utf-8')
</code></pre>

<p>现在再运行，就正常了：</p>

<pre><code>你好，AoboSir。
</code></pre>

<hr />

<h2>搞定</h2>
]]></content>
  </entry>
  
</feed>
